from DS import *

my_priority_queu = PriorityQueue(5)
my_priority_queu.Enqueue(PriorityQueue.PriorityItem(1, PriorityQueue.PriorityItem.Priority.LOW))
print(my_priority_queu.peek_front(),my_priority_queu.peek_back())
my_priority_queu.Enqueue(PriorityQueue.PriorityItem(2, PriorityQueue.PriorityItem.Priority.HIGH))
print(my_priority_queu.peek_front(),my_priority_queu.peek_back())
my_priority_queu.Enqueue(PriorityQueue.PriorityItem(3, PriorityQueue.PriorityItem.Priority.MID))
print(my_priority_queu.peek_front(),my_priority_queu.peek_back())
my_priority_queu.Enqueue(PriorityQueue.PriorityItem(4, PriorityQueue.PriorityItem.Priority.HIGH))
my_priority_queu.Dequeue()
print(my_priority_queu.peek_front(),my_priority_queu.peek_back())
my_priority_queu.Enqueue(PriorityQueue.PriorityItem(5, PriorityQueue.PriorityItem.Priority.MID))
print(PriorityQueue.get_items(my_priority_queu))
# my_queue_circle = QueueCircle(Max=4)
# my_queue_circle.Enqueue(1)
# my_queue_circle.Enqueue(2)
# my_queue_circle.Enqueue(3)
# my_queue_circle.Enqueue(4)
# print(my_queue_circle.peek_front())
# my_queue_circle.Dequeue()
# print(my_queue_circle.peek_front())
# my_queue_circle.Enqueue(5)
# my_queue_circle.Dequeue()
# print(my_queue_circle.peek_front())
# my_queue_circle.Enqueue(6)
# print(my_queue_circle.peek_front())
# print(my_queue_circle.peek_back())
# my_queue_ls = QueueLS(4)
# my_queue_ls.Enqueue(2)
# my_queue_ls.Enqueue(5)
# print(my_queue_ls.peek_back())
# print(my_queue_ls.peek_front())
# my_queue_ls.Dequeue()
# print(my_queue_ls.peek_back())
# print(my_queue_ls.peek_front())
# my_queue_ls.Dequeue()
# print(my_queue_ls.peek_back())
# print(my_queue_ls.peek_front())
# my_ls = LinkedList()
# my_ls2 = my_ls
# my_ls2.next = LinkedList(2)
# my_ls2=my_ls2.next
# my_ls2.next = LinkedList(3)
# my_ls.travel(2)
# my_ls.travel(1)
# print(my_ls.val)
# my_queue = QueueArr(4, 'i')
# my_queue.Enqueue(5)
# my_queue.Enqueue(6)
# my_queue.Enqueue(7)
# my_queue.Enqueue(8)
# my_queue.Dequeue()
# print(my_queue.peek_back())
# print(my_queue.peek_front())