from DS import *

my_queue_ls = QueueLS(4)
my_queue_ls.Enqueue(2)
my_queue_ls.Enqueue(5)
print(my_queue_ls.peek_back())
print(my_queue_ls.peek_front())
my_queue_ls.Dequeue()
print(my_queue_ls.peek_back())
print(my_queue_ls.peek_front())
my_queue_ls.Dequeue()
print(my_queue_ls.peek_back())
print(my_queue_ls.peek_front())
# my_ls = LinkedList()
# my_ls2 = my_ls
# my_ls2.next = LinkedList(2)
# my_ls2=my_ls2.next
# my_ls2.next = LinkedList(3)
# my_ls.travel(2)
# my_ls.travel(1)
# print(my_ls.val)
# my_queue = QueueArr(4, 'i')
# my_queue.Enqueue(5)
# my_queue.Enqueue(6)
# my_queue.Enqueue(7)
# my_queue.Enqueue(8)
# my_queue.Dequeue()
# print(my_queue.peek_back())
# print(my_queue.peek_front())